### ISSUE TITLE
Create the project structure

### ISSUE THREAD

**Issue by aslv-consulting** [aslv-consulting/mycareer#1]
## Description

Create the project structure with python and tkinter. 
these services must be configured : pylint, pytest, mkdocs, database and migration.

## Subtasks

- [x] Create the git structure (README, CHANGELOG ...).
- [x] Create the window.
- [x] Create the database and migration system.
- [x] Generate the documentation.
- [x] Generate and integrate the test coverage to documentation.
- [x] Configure the GitHub issue templates.
- [x] Configure the git commit template.
- [x] Configure a CI to generate the GitHub pages for the documentation.

## Done criteria

- [ ] **Feature implemented**: Code is written, compiled, and functions as per the requirements.
- [ ] **Tests**: Tests are written, executed, and pass with an acceptable coverage rate.
- [ ] **Linter**: Linter must have zero error.
- [ ] **Documentation**:  Relevant documentation  is written and updated.
