### ISSUE TITLE
Documentation for the project

### ISSUE THREAD

**Issue by aslv-consulting** [aslv-consulting/mycareer#2]
## Description

The documentation is a default documentation.
Create a documentation for the project.

## Subtasks

- [ ] Update documentation
- [ ] Make a  style

## Done Criteria

- [ ] **Feature implemented**: Code is written, compiled, and functions as per the requirements.
- [ ] **Tests**: Tests are written, executed, and pass with an acceptable coverage rate.
- [ ] **Linter**:  Linter must have zero error.
- [ ] **Documentation**:  Relevant documentation (code, API, usage, etc.) is written and updated.
