### ISSUE TITLE
Create the main interface

### ISSUE THREAD

**Issue by aslv-consulting** [aslv-consulting/mycareer#5]
## User story

As a user, I want to have an interface so that I use the app.

## Subtasks

- [ ] Configure the main layout.
- [ ] Configure the main navigation.

## Done criteria

- [ ] **Feature implemented**: Code is written, compiled, and functions as per the requirements.
- [ ] **Tests**: Tests are written, executed, and pass with an acceptable coverage rate.
- [ ] **Linter**:  Linter must have zero error.
- [ ] **Documentation**:  Relevant documentation is written and updated.
